class ChessLesson {
  const ChessLesson({
    required this.title,
    required this.category,
    required this.description,
    required this.instruction,
    required this.fen,
    required this.acceptedMoves,
    required this.hint,
    required this.success,
  });

  final String title;
  final String category;
  final String description;
  final String instruction;
  final String fen;
  final Set<String> acceptedMoves;
  final String hint;
  final String success;
}

const lessonCatalog = <ChessLesson>[
  ChessLesson(
    title: 'O primeiro passo',
    category: 'PEÃO',
    description: 'Peões andam para frente e capturam na diagonal.',
    instruction: 'Leva o peão de e2 até e4 em um único lance.',
    fen: '7k/8/8/8/8/8/4P3/4K3 w - - 0 1',
    acceptedMoves: {'e2e4'},
    hint: 'No primeiro movimento, o peão pode avançar duas casas.',
    success: 'Boa! Depois disso ele passa a andar somente uma casa por vez.',
  ),
  ChessLesson(
    title: 'A torre é um trem',
    category: 'TORRE',
    description: 'Ela cruza linhas e colunas, mas nunca faz curva.',
    instruction: 'Move a torre de a1 até a8.',
    fen: '7k/8/8/8/8/8/8/R6K w - - 0 1',
    acceptedMoves: {'a1a8'},
    hint: 'Sobe reto pela coluna a. Não tem nenhuma peça bloqueando.',
    success: 'Perfeito. Torres ficam especialmente fortes em colunas abertas.',
  ),
  ChessLesson(
    title: 'Cortando na diagonal',
    category: 'BISPO',
    description: 'O bispo atravessa o tabuleiro pelas diagonais.',
    instruction: 'Leva o bispo de c1 até h6.',
    fen: '7k/8/8/8/8/8/8/2B4K w - - 0 1',
    acceptedMoves: {'c1h6'},
    hint: 'Segue pelas casas d2, e3, f4, g5 e h6.',
    success: 'Isso aí. Um bispo nunca muda a cor das casas em que joga.',
  ),
  ChessLesson(
    title: 'O cavalo diferentão',
    category: 'CAVALO',
    description: 'Ele anda em L e é a única peça que pula outras peças.',
    instruction: 'Salta com o cavalo de g1 para f3.',
    fen: '7k/8/8/8/8/8/8/6NK w - - 0 1',
    acceptedMoves: {'g1f3'},
    hint: 'Duas casas para cima e uma para o lado: esse é o L.',
    success: 'Acertou. Cavalos adoram o centro e detestam os cantos.',
  ),
  ChessLesson(
    title: 'A peça mais poderosa',
    category: 'DAMA',
    description: 'A dama combina os movimentos da torre e do bispo.',
    instruction: 'Move a dama de d1 até h5.',
    fen: '7k/8/8/8/8/8/8/3Q3K w - - 0 1',
    acceptedMoves: {'d1h5'},
    hint: 'Dessa vez ela vai pela diagonal: e2, f3, g4, h5.',
    success: 'Mandou bem. Só não coloca a dama em perigo cedo demais.',
  ),
  ChessLesson(
    title: 'Captura e pressão',
    category: 'CAPTURA',
    description: 'Uma peça pode ocupar a casa de uma inimiga e removê-la.',
    instruction: 'A torre preta está desprotegida. Captura ela.',
    fen: 'r6k/8/8/8/8/8/8/R6K w - - 0 1',
    acceptedMoves: {'a1a8'},
    hint: 'As duas torres estão na mesma coluna e não há nada entre elas.',
    success: 'Captura limpa — e ainda veio com xeque no rei preto.',
  ),
  ChessLesson(
    title: 'Atacando o rei',
    category: 'XEQUE',
    description: 'Xeque é um ataque direto ao rei adversário.',
    instruction: 'Move a torre para a oitava fileira e dá xeque.',
    fen: '7k/8/8/8/8/8/8/4R2K w - - 0 1',
    acceptedMoves: {'e1e8'},
    hint: 'Na casa e8, a torre vai enxergar o rei pela horizontal.',
    success: 'Xeque! Agora o adversário seria obrigado a resolver a ameaça.',
  ),
  ChessLesson(
    title: 'Mate em um',
    category: 'TÁTICA',
    description: 'O rei preto está preso. Falta encontrar o golpe final.',
    instruction: 'Encontra o xeque-mate em apenas um lance.',
    fen: '7k/5Q2/6K1/8/8/8/8/8 w - - 0 1',
    acceptedMoves: {'f7g7'},
    hint: 'A dama pode chegar em g7 protegida pelo teu rei.',
    success: 'Xeque-mate! O rei não consegue fugir nem capturar a dama.',
  ),
  ChessLesson(
    title: 'Protege o rei',
    category: 'ROQUE',
    description: 'O roque move rei e torre juntos para buscar segurança.',
    instruction: 'Faz o roque pequeno das brancas.',
    fen: 'r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1',
    acceptedMoves: {'e1g1'},
    hint: 'Seleciona o rei em e1 e leva ele duas casas até g1.',
    success: 'Rei protegido e torre ativada — dois problemas resolvidos de uma vez.',
  ),
  ChessLesson(
    title: 'En passant sem mistério',
    category: 'REGRA ESPECIAL',
    description: 'Um peão que avançou duas casas pode ser capturado de passagem.',
    instruction: 'Faz a captura en passant com o peão branco.',
    fen: '7k/8/8/3pP3/8/8/8/7K w - d6 0 2',
    acceptedMoves: {'e5d6'},
    hint: 'Move o peão de e5 para d6, como se o peão preto tivesse andado só uma.',
    success: 'É esquisito na primeira vez, mas agora tu já conhece o famoso en passant.',
  ),
  ChessLesson(
    title: 'Peão também captura',
    category: 'PEÃO',
    description: 'Para andar ele vai reto; para capturar, vai na diagonal.',
    instruction: 'Captura o peão preto que está em d4.',
    fen: '7k/8/8/8/3p4/4P3/8/7K w - - 0 1',
    acceptedMoves: {'e3d4'},
    hint: 'O peão branco em e3 captura uma casa para cima e para o lado.',
    success: 'Boa! Movimento e captura do peão seguem regras diferentes.',
  ),
  ChessLesson(
    title: 'Garfo de cavalo',
    category: 'TÁTICA',
    description: 'Um único cavalo pode atacar duas peças valiosas ao mesmo tempo.',
    instruction: 'Encontra o salto que ataca o rei e a dama.',
    fen: 'k7/3q4/8/8/2N5/8/8/7K w - - 0 1',
    acceptedMoves: {'c4b6'},
    hint: 'Procura uma casa de onde o cavalo alcance a8 e d7.',
    success: 'Nb6+! O rei precisa reagir e a dama fica para depois.',
  ),
  ChessLesson(
    title: 'Cravada absoluta',
    category: 'TÁTICA',
    description: 'Uma peça cravada não pode sair se isso expuser o próprio rei.',
    instruction: 'Posiciona o bispo para cravar o cavalo ao rei.',
    fen: '4k3/3n4/8/8/B7/8/8/7K w - - 0 1',
    acceptedMoves: {'a4b5'},
    hint: 'Alinha o bispo, o cavalo de d7 e o rei de e8.',
    success: 'Bb5! Agora o cavalo está preso na diagonal do rei.',
  ),
  ChessLesson(
    title: 'Espeto na diagonal',
    category: 'TÁTICA',
    description: 'No espeto, a peça mais valiosa fica na frente de outra.',
    instruction: 'Dá xeque e deixa a dama escondida atrás do rei.',
    fen: '7q/6k1/8/8/8/8/8/2B4K w - - 0 1',
    acceptedMoves: {'c1b2'},
    hint: 'A diagonal b2–h8 atravessa o rei e termina na dama.',
    success: 'Bb2+! Quando o rei sair, a dama em h8 ficará exposta.',
  ),
  ChessLesson(
    title: 'Ataque descoberto',
    category: 'TÁTICA',
    description: 'Uma peça sai do caminho e revela o ataque de outra.',
    instruction: 'Tira o bispo da coluna e revela a torre contra a dama.',
    fen: '4k3/4q3/8/8/8/8/4B3/4R2K w - - 0 1',
    acceptedMoves: {'e2b5'},
    hint: 'O bispo pode sair pela diagonal até b5.',
    success: 'A torre ganhou visão pela coluna e atacou a dama.',
  ),
  ChessLesson(
    title: 'Mate na última fileira',
    category: 'XEQUE-MATE',
    description: 'Os próprios peões podem formar uma prisão para o rei.',
    instruction: 'Encontra o mate de torre na oitava fileira.',
    fen: '6k1/5ppp/8/8/8/8/8/4R2K w - - 0 1',
    acceptedMoves: {'e1e8'},
    hint: 'A torre pode subir até e8. Os peões fecham as fugas do rei.',
    success: 'Re8# — um padrão de mate que aparece o tempo todo.',
  ),
  ChessLesson(
    title: 'Bloqueia o xeque',
    category: 'DEFESA',
    description: 'Nem todo xeque exige mover o rei: às vezes dá para bloquear.',
    instruction: 'Coloca o bispo entre a torre preta e o teu rei.',
    fen: '4r2k/8/8/8/8/8/8/2B1K3 w - - 0 1',
    acceptedMoves: {'c1e3'},
    hint: 'A casa e3 fica bem no meio da coluna do ataque.',
    success: 'Be3! O bispo virou um escudo e o rei está seguro.',
  ),
  ChessLesson(
    title: 'Chegou na última casa',
    category: 'PROMOÇÃO',
    description: 'Um peão que alcança o fim pode virar uma peça muito mais forte.',
    instruction: 'Leva o peão de a7 até a8 e promove.',
    fen: '7k/P7/8/8/8/8/8/7K w - - 0 1',
    acceptedMoves: {'a7a8'},
    hint: 'É só avançar uma casa; o JChess vai transformar ele em dama.',
    success: 'Promoção! Um peão paciente acabou virando a peça mais poderosa.',
  ),
  ChessLesson(
    title: 'Corre, peão passado',
    category: 'FINAL',
    description: 'Sem peões inimigos pela frente ou ao lado, o caminho está livre.',
    instruction: 'Avança o peão passado e aproxima ele da promoção.',
    fen: '7k/p6p/8/3P4/8/8/8/7K w - - 0 1',
    acceptedMoves: {'d5d6'},
    hint: 'Nenhum peão preto consegue parar o peão de d5 diretamente.',
    success: 'd6! Peão passado tem vocação para correr.',
  ),
  ChessLesson(
    title: 'Mate com torre e rei',
    category: 'FINAL',
    description: 'O rei fecha as fugas enquanto a torre entrega o xeque.',
    instruction: 'Encontra o mate em um com a torre.',
    fen: '7k/5K2/8/8/8/8/8/R7 w - - 0 1',
    acceptedMoves: {'a1h1'},
    hint: 'Leva a torre para a mesma coluna do rei preto.',
    success: 'Rh1# — a torre dá xeque e o teu rei controla a fuga por g8.',
  ),
  ChessLesson(
    title: 'Garfo de dama',
    category: 'TÁTICA',
    description: 'A dama também consegue atacar rei e torre de uma só vez.',
    instruction: 'Dá xeque enquanto ataca a torre de a8.',
    fen: 'r6k/8/8/8/3Q4/8/8/7K w - - 0 1',
    acceptedMoves: {'d4d8'},
    hint: 'Na oitava fileira, a dama enxerga os dois lados.',
    success: 'Qd8+! Depois que o rei sair, a torre fica pendurada.',
  ),
  ChessLesson(
    title: 'Desenvolve com tempo',
    category: 'ABERTURA',
    description: 'No começo, coloca as peças em jogo e disputa o centro.',
    instruction: 'Desenvolve o cavalo do rei para uma casa central.',
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    acceptedMoves: {'g1f3'},
    hint: 'O cavalo de g1 fica mais ativo em f3.',
    success: 'Nf3: uma peça fora da garagem e mais controle do centro.',
  ),
  ChessLesson(
    title: 'Briga pelo centro',
    category: 'ABERTURA',
    description: 'Quem controla o centro costuma ter mais espaço para manobrar.',
    instruction: 'Ocupa o centro com um dos peões principais.',
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    acceptedMoves: {'d2d4', 'e2e4'},
    hint: 'Os peões de d2 e e2 podem avançar duas casas no primeiro lance.',
    success: 'Centro ocupado. Agora desenvolve as peças e protege o rei.',
  ),
  ChessLesson(
    title: 'Remove o defensor',
    category: 'TÁTICA',
    description: 'Às vezes a melhor captura é a peça que protege todo o resto.',
    instruction: 'Captura o cavalo que defende as casas do rei.',
    fen: '7k/7p/5n2/6B1/8/8/8/7K w - - 0 1',
    acceptedMoves: {'g5f6'},
    hint: 'O bispo em g5 pode eliminar o cavalo de f6.',
    success: 'Bxf6! Primeiro cai o defensor; depois aparecem os alvos.',
  ),
];
